export const TZ_PENDING_FETCH_LIST_DATA = 'TZ_PENDING_FETCH_LIST_DATA';
export const TZ_SUCCESS_FETCH_LIST_DATA = 'TZ_SUCCESS_FETCH_LIST_DATA';
export const TZ_FAILED_FETCH_LIST_DATA = 'TZ_FAILED_FETCH_LIST_DATA';
export const TZ_FINISH_FETCH_LIST_DATA = 'TZ_FINISH_FETCH_LIST_DATA';
