export const WT_PENDING_FETCH_DATA = 'WT_PENDING_FETCH_DATA';
export const WT_SUCCESS_FETCH_DATA = 'WT_SUCCESS_FETCH_DATA';
export const WT_FAILED_FETCH_DATA = 'WT_FAILED_FETCH_DATA';
export const WT_FINISH_FETCH_DATA = 'WT_FINISH_FETCH_DATA';
